services:
  cache:
    container_name: "cache"
    image: "docker.io/library/redis:7.4"
    environment:
      REDIS_PASSWORD: "YwlK0K6H0ACBC3FOzYEy5z"
    ports:
    - target: 6379
      published: 6379
    command:
    - "-c"
    - "redis-server --requirepass $REDIS_PASSWORD"
    - "/bin/sh"
    restart: unless-stopped

  db:
    container_name: "db"
    image: "docker.io/library/postgres:17.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "7tU!5vSkMWoiU4Pa!XzS13"
    ports:
    - target: 5432
      published: 5432
    volumes:
    - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  apiservice:
    container_name: "apiservice"
    image: "futsal/apiservice:latest"
    environment:
      ASPNETCORE_URLS: "http://+:8080;http://+:8000"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080;8000"
      ConnectionStrings__db: "Host=db;Port=5432;Username=postgres;Password=7tU!5vSkMWoiU4Pa!XzS13"
      ConnectionStrings__cache: "cache:6379,password=YwlK0K6H0ACBC3FOzYEy5z"
    ports:
    - target: 8080
      published: 10000
    - target: 8000
      published: 10002
    restart: unless-stopped

volumes:
  db_data:
