name: Futsal API CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Generate Docker Compose files using Aspire
      - name: Generate Docker Compose
        run: |
          mkdir -p ./publish
          dotnet publish FutsalApi/FutsalApi.AppHost --os linux --arch x64 /t:PublishContainer --publisher dockercompose --output ./publish

      # Clean up previous deployment
      - name: Clean Previous Deployment
        run: |
          sudo mkdir -p /home/${{ secrets.DO_USERNAME }}/app
          sudo chown -R $USER:$USER /home/${{ secrets.DO_USERNAME }}/app

          cd /home/${{ secrets.DO_USERNAME }}/app
          sudo docker-compose -p futsalapi down || true
          sudo docker system prune -f || true

      # Copy new deployment files
      - name: Copy Deployment Files
        run: |
          cp -r ./publish/* /home/${{ secrets.DO_USERNAME }}/app/

      # Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          cd /home/${{ secrets.DO_USERNAME }}/app

          # Start the application
          sudo docker-compose -p futsalapi up -d --build

          # Wait for containers to be ready
          sleep 15

          # Verify deployment
          if sudo docker ps | grep -q "futsalapi"; then
            echo "✅ Deployment successful"
            sudo docker ps --filter "name=futsalapi"
          else
            echo "❌ Deployment failed"
            sudo docker-compose -p futsalapi logs
            exit 1
          fi
