name: Build & Test with Solution

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted  

    steps:
    - name: Restore dependencies
      run: dotnet restore /app/FutsalApi.sln

    - name: Format check
      run: dotnet format /app/FutsalApi.sln --verify-no-changes

    - name: Build solution
      run: dotnet build /app/FutsalApi.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test /app/FutsalApi.sln --no-build --verbosity normal
