name: Build & Test with Solution

on:
  push:
    branches: [master]

jobs:
  test-build-run:
    runs-on: self-hosted

    steps:
      - name: Restore dependencies
        run: dotnet restore /app/FutsalApi.sln

      # - name: Format check
      #   run: dotnet format /app/FutsalApi.sln --verify-no-changes

      - name: Build solution
        run: dotnet build /app/FutsalApi.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test /app/FutsalApi.sln --no-build --verbosity normal

      # - name: Publish ApiService
      #   run: cd /app/FutsalApi.ApiService && aspirate build

      # - name: Run ApiService DLL
      #   run: dotnet /app/publish/FutsalApi.ApiService.dll --urls "http://0.0.0.0:7576;"
