name: Futsal API CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Generate Docker Compose file using Aspire
      - name: Generate Docker Compose
        run: |
          mkdir -p ./publish
          cd FutsalApi/FutsalApi.AppHost
          aspirate generate --output-format compose --output-path ../../publish

      - name: Deploy Application
        run: |
          APP_DIR="/home/${{ secrets.DO_USERNAME }}/app"
          sudo mkdir -p $APP_DIR
          sudo chown -R $USER:$USER $APP_DIR
          cd $APP_DIR
          sudo docker-compose -p futsalapi down || true
          sudo docker system prune -f || true
          sudo cp -r ${{ github.workspace }}/publish/* .
          sudo docker-compose -p futsalapi up -d --build
          sleep 15
          if sudo docker ps | grep -q "futsalapi"; then
            echo "✅ Deployment successful"
            sudo docker ps --filter "name=futsalapi"
          else
            echo "❌ Deployment failed"
            sudo docker-compose -p futsalapi logs
            exit 1
          fi
