name: Aspire CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Create manifest in runner's workspace first
      - name: Generate Manifest Locally
        run: |
          mkdir -p ./publish
          dotnet run --project FutsalApi/FutsalApi.AppHost --publisher manifest --output-path ./publish/manifest.json

      # Fix permissions and prepare environment
      - name: Prepare Deployment Directory
        run: |
          # Create directory with correct ownership
          sudo mkdir -p /home/${{ secrets.DO_USERNAME }}/app
          sudo chown -R $USER:$USER /home/${{ secrets.DO_USERNAME }}/app

          # Clean up Docker containers
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true

      # Copy manifest to app directory
      - name: Copy Manifest
        run: |
          cp ./publish/manifest.json /home/${{ secrets.DO_USERNAME }}/app/

      - name: Deploy Application
        run: |
          cd /home/${{ secrets.DO_USERNAME }}/app

          # Install Aspire CLI if needed
          if ! command -v aspire &> /dev/null; then
            dotnet tool install -g Microsoft.Extensions.Hosting.Aspire
            echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          fi

          # Deploy the application
          aspire deploy --manifest manifest.json
