name: CI/CD Pipeline

on: [push]

jobs:
  format-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Specify the .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Run code formatting check
      - name: Check code formatting
        run: dotnet format --check
        continue-on-error: true # Allow the workflow to continue even if formatting issues are found

      # Step 5: Run unit tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal