name: Aspire CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and generate manifest
        run: |
          # Generate manifest directly in the app directory
          mkdir -p /home/${{ secrets.DO_USERNAME }}/app
          dotnet run --project FutsalApi/FutsalApi.AppHost --publisher manifest --output-path /home/${{ secrets.DO_USERNAME }}/app/manifest.json

      - name: Prepare environment
        run: |
          # Stop and clean up any previous containers
          if [ "$(docker ps -q)" ]; then
            docker stop $(docker ps -q)
          fi
          if [ "$(docker ps -aq)" ]; then
            docker rm $(docker ps -aq)
          fi

      - name: Deploy using Aspire Manifest
        run: |
          cd /home/${{ secrets.DO_USERNAME }}/app
          # Install Aspire CLI if needed
          if ! command -v aspire &> /dev/null; then
            dotnet tool install -g Microsoft.Extensions.Hosting.Aspire
          fi

          # Deploy the application
          aspire deploy --manifest manifest.json
