name: Aspire CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Publish Aspire App Manifest
        run: |
          # Generate the manifest files (Aspire workload should already be installed on the runner)
          # IMPORTANT: Use ${{ github.workspace }}/publish to ensure the 'publish' directory is created
          # directly in the root of the GitHub Actions workspace, making it accessible for subsequent steps.
          dotnet run --project FutsalApi/FutsalApi.AppHost --publisher manifest --output-path ${{ github.workspace }}/publish

      - name: Debug - List publish directory contents
        run: |
          echo "Contents of ./publish directory:"
          # Use -la for more detailed listing, including permissions and hidden files
          ls -la ./publish || echo "Publish directory does not exist or is empty"
          echo "Contents of current directory:"
          ls -la .
          echo "Total files in publish directory (if exists):"
          # Find files and count them, suppressing errors if directory doesn't exist
          find ./publish -type f 2>/dev/null | wc -l || echo "0"

      - name: Deploy to DigitalOcean - Prepare remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            # Stop and remove any previous containers gracefully
            # Check if there are any running containers before attempting to stop
            if docker ps -q | grep .; then
              echo "Stopping running Docker containers..."
              docker stop $(docker ps -q)
            else
              echo "No running Docker containers to stop."
            fi
            # Check if there are any existing containers (running or stopped) before attempting to remove
            if docker ps -aq | grep .; then
              echo "Removing all Docker containers..."
              docker rm $(docker ps -aq)
            else
              echo "No Docker containers to remove."
            fi
            # Remove the old app directory if it exists
            if [ -d "/home/${{ secrets.DO_USERNAME }}/app" ]; then
              echo "Removing old app directory..."
              rm -rf /home/${{ secrets.DO_USERNAME }}/app
            else
              echo "App directory does not exist, skipping removal."
            fi
            # Create a new directory for the app
            echo "Creating new app directory..."
            mkdir -p /home/${{ secrets.DO_USERNAME }}/app

      - name: Copy published files to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          # This will now correctly point to the 'publish' directory at the repository root
          source: "publish/*"
          target: "/home/${{ secrets.DO_USERNAME }}/app"
          strip_components: 1

      - name: Deploy using Aspire Manifest
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd /home/${{ secrets.DO_USERNAME }}/app
            # Check if manifest.json exists
            if [ -f "manifest.json" ]; then
              echo "Found manifest.json, deploying using Aspire manifest..."
              # Install aspire CLI if not already installed
              # Using 'which' to check for existence and only install if not found
              if ! command -v aspire &> /dev/null; then
                echo "Aspire CLI not found, installing..."
                dotnet tool install -g Microsoft.Extensions.Hosting.Aspire
              else
                echo "Aspire CLI already installed."
              fi
              # Deploy using the manifest
              aspire deploy --manifest manifest.json
            else
              echo "No manifest.json found, listing available files:"
              ls -la
              # Fallback to docker compose if docker-compose.yml exists
              if [ -f "docker-compose.yml" ]; then
                echo "Found docker-compose.yml, using docker compose..."
                docker compose up -d --build
              elif [ -f "compose.yaml" ]; then
                echo "Found compose.yaml, using docker compose..."
                docker compose up -d --build
              else
                echo "No deployment files found! Exiting."
                exit 1
              fi
            fi
