name: Code Style Check

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0 # Use a .NET 9.0 SDK image
    steps:
      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format
        env:
          PATH: $HOME/.dotnet:$PATH
      - name: Run dotnet format
        run: dotnet format --check
        env:
          PATH: $HOME/.dotnet:$PATH
