name: Code Style Check

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0 # Use a .NET 9.0 SDK image
    steps:
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add -
          echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get install -y docker-ce docker-ce-cli containerd.io
          usermod -aG docker $USER
          newgrp docker

      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format
        env:
          PATH: $HOME/.dotnet:$PATH
      - name: Run dotnet format
        run: dotnet format --check
        env:
          PATH: $HOME/.dotnet:$PATH
